### ISSUE TITLE
Compiler Compatibility V1.1-1

### ISSUE THREAD

**Issue by violaglenn** [mhahsler/dbscan#13] opened 2017-04-10 15:13 UTC
I'm not able to load dbscan starting with V1.1-0 in what appears to be a compiler issue.  Any thoughts?

**Details:**

No trouble getting v 1.0 -- 
install.packages("dbscan", repos = "https://mran.revolutionanalytics.com/snapshot/2017-03-19")

Installing package into ‘/work/library/3.3.1’
(as ‘lib’ is unspecified)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  765k  100  765k    0     0  2974k      0 --:--:-- --:--:-- --:--:-- 2978k
* installing *source* package ‘dbscan’ ...
** package ‘dbscan’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/lib64/microsoft-open-r/3.3.1/microsoft-r/3.3/lib64/R/include -DNDEBUG  -DU_STATIC_IMPLEMENTATION -I"/work/library/3.3.1/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATIN -O2 -g  -c ANN.cpp -o ANN.o
g++ -I/usr/lib64/microsoft-open-r/3.3.1/microsoft-r/3.3/lib64/R/include -DNDEBUG  -DU_STATIC_IMPLEMENTATION -I"/work/library/3.3.1/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATIN -O2 -g  -c R_JP.cpp -o R_JP.o
g++ -I/usr/lib64/microsoft-open-r/3.3.1/microsoft-r/3.3/lib64/R/include -DNDEBUG  -DU_STATIC_IMPLEMENTATION -I"/work/library/3.3.1/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATIN -O2 -g  -c R_dbscan.cpp -o R_dbscan.o

Anything after is missing the g++ bash and returns non-zero exit status:
install.packages("dbscan", repos = "https://mran.revolutionanalytics.com/snapshot/2017-03-20")

Installing package into ‘/work/library/3.3.1’
(as ‘lib’ is unspecified)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100 2031k  100 2031k    0     0  7531k      0 --:--:-- --:--:-- --:--:-- 7550k
* installing *source* package ‘dbscan’ ...
** package ‘dbscan’ successfully unpacked and MD5 sums checked
** libs
I/usr/lib64/microsoft-open-r/3.3.1/microsoft-r/3.3/lib64/R/include -DNDEBUG  -DU_STATIC_IMPLEMENTATION -I"/work/library/3.3.1/Rcpp/include"      -c ANN.cpp -o ANN.o
sh: I/usr/lib64/microsoft-open-r/3.3.1/microsoft-r/3.3/lib64/R/include: No such file or directory
make: [ANN.o] Error 127 (ignored)
I/usr/lib64/microsoft-open-r/3.3.1/microsoft-r/3.3/lib64/R/include -DNDEBUG  -DU_STATIC_IMPLEMENTATION -I"/work/library/3.3.1/Rcpp/include"      -c R_JP.cpp -o R_JP.o
sh: I/usr/lib64/microsoft-open-r/3.3.1/microsoft-r/3.3/lib64/R/include: No such file or directory
make: [R_JP.o] Error 127 (ignored)

_We've lost the g++ call to bash._ 

**Details on my setup:**
platform       x86_64-pc-linux-gnu         
version.string R version 3.3.1 (2016-06-21)
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) (should handle CC++ 11 just fine)

**Comment by peekxc** [comment] 2017-04-12 15:23
viola, 

I will look into this sometime later this week; I'm unable to reproduce the issue at least with Ubuntu 16.06, using gcc . In the mean time, have you looked at this?
 
https://github.com/Microsoft/microsoft-r-open/issues/11

It may be the case that the microsoft's open R--despite their claims--is not 100% compatible with all packages, or more specifically the package build scripts. The fix in that issue didn't relate so much to the package, but rather, an incompatibility in the make conf.

**Comment by peekxc** [comment] 2017-04-21 23:16
@violaglenn Just to double-check, you have the ability to install other packages I assume? For example, do you have fpc installed?

**Comment by violaglenn** [comment] 2017-04-25 18:18
@peekxc Sorry for the delay-- just digging back into this today, and we are seeing this elsewhere, so I'm thinking it is related to the open R compiler. I've migrated my question over there. 

Thank you!

**Comment by mhahsler** [comment] 2017-04-27 03:19
Closing issue since it seems to be related to the compiler and not to the package.

**Closed as completed by mhahsler** 2017-04-27 03:19 UTC
Labels: invalid
